language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
install: true
env:
  matrix:
    - XCODE_SCHEME=libPusher SDK=iphonesimulator
    - XCODE_SCHEME=libPusher-OSX SDK=macosx10.9
script: xctool -workspace libPusher.xcworkspace -scheme $XCODE_SCHEME -sdk $SDK build test
